// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/solana.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestBlockHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestBlockHashRequest) Reset() {
	*x = GetLatestBlockHashRequest{}
	mi := &file_proto_solana_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockHashRequest) ProtoMessage() {}

func (x *GetLatestBlockHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_solana_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockHashRequest.ProtoReflect.Descriptor instead.
func (*GetLatestBlockHashRequest) Descriptor() ([]byte, []int) {
	return file_proto_solana_proto_rawDescGZIP(), []int{0}
}

type GetLatestBlockHashResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Blockhash            string                 `protobuf:"bytes,1,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	LastValidBlockHeight int32                  `protobuf:"varint,2,opt,name=last_valid_block_height,json=lastValidBlockHeight,proto3" json:"last_valid_block_height,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetLatestBlockHashResponse) Reset() {
	*x = GetLatestBlockHashResponse{}
	mi := &file_proto_solana_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockHashResponse) ProtoMessage() {}

func (x *GetLatestBlockHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_solana_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockHashResponse.ProtoReflect.Descriptor instead.
func (*GetLatestBlockHashResponse) Descriptor() ([]byte, []int) {
	return file_proto_solana_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestBlockHashResponse) GetBlockhash() string {
	if x != nil {
		return x.Blockhash
	}
	return ""
}

func (x *GetLatestBlockHashResponse) GetLastValidBlockHeight() int32 {
	if x != nil {
		return x.LastValidBlockHeight
	}
	return 0
}

var File_proto_solana_proto protoreflect.FileDescriptor

const file_proto_solana_proto_rawDesc = "" +
	"\n" +
	"\x12proto/solana.proto\x12\x05proto\"\x1b\n" +
	"\x19GetLatestBlockHashRequest\"q\n" +
	"\x1aGetLatestBlockHashResponse\x12\x1c\n" +
	"\tblockhash\x18\x01 \x01(\tR\tblockhash\x125\n" +
	"\x17last_valid_block_height\x18\x02 \x01(\x05R\x14lastValidBlockHeight2j\n" +
	"\rSolanaService\x12Y\n" +
	"\x12GetLatestBlockHash\x12 .proto.GetLatestBlockHashRequest\x1a!.proto.GetLatestBlockHashResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_solana_proto_rawDescOnce sync.Once
	file_proto_solana_proto_rawDescData []byte
)

func file_proto_solana_proto_rawDescGZIP() []byte {
	file_proto_solana_proto_rawDescOnce.Do(func() {
		file_proto_solana_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_solana_proto_rawDesc), len(file_proto_solana_proto_rawDesc)))
	})
	return file_proto_solana_proto_rawDescData
}

var file_proto_solana_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_solana_proto_goTypes = []any{
	(*GetLatestBlockHashRequest)(nil),  // 0: proto.GetLatestBlockHashRequest
	(*GetLatestBlockHashResponse)(nil), // 1: proto.GetLatestBlockHashResponse
}
var file_proto_solana_proto_depIdxs = []int32{
	0, // 0: proto.SolanaService.GetLatestBlockHash:input_type -> proto.GetLatestBlockHashRequest
	1, // 1: proto.SolanaService.GetLatestBlockHash:output_type -> proto.GetLatestBlockHashResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_solana_proto_init() }
func file_proto_solana_proto_init() {
	if File_proto_solana_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_solana_proto_rawDesc), len(file_proto_solana_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_solana_proto_goTypes,
		DependencyIndexes: file_proto_solana_proto_depIdxs,
		MessageInfos:      file_proto_solana_proto_msgTypes,
	}.Build()
	File_proto_solana_proto = out.File
	file_proto_solana_proto_goTypes = nil
	file_proto_solana_proto_depIdxs = nil
}
